services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - PYTHONPATH=/app
      # NEW: Session management environment variables
      - SESSION_STORAGE_PATH=/app/data/sessions
      - SESSION_MAX_AGE_HOURS=24
    volumes:
      - ./app:/app/app
      - ./app/data:/app/data
      - ./data/sessions:/app/data/sessions  # NEW: Session storage volume
      - ./vector_data:/app/vector_data
      - ./logs:/app/logs
      - ./cache:/app/cache
    depends_on:
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
